var app=new Vue({
    el:"#app",
    data:{
        columns:[
            {
                title:"姓名",
                key:"name"
            },
            {
                title:"年龄",
                key:"age",
                sortable:true
            },
            {
                title:'出生日期',
                key:"birthday",
                sortable:true
            },
            {
                title:"地址",
                key:"address"
            }
        ],
        data:[
            {
                name:"王小明",
                age:18,
                birthday:"1999-02-21",
                address:"北京市朝阳区"
            },
            {
                name:"王小明1",
                age:181,
                birthday:"1990-02-21",
                address:"北京市朝阳区1"
            },
            {
                name:"王小明",
                age:21,
                birthday:"1991-02-21",
                address:"北京市朝阳区"
            },
            {
                name:"王小明",
                age:35,
                birthday:"1995-02-21",
                address:"北京市朝阳区"
            },
            {
                name:"王小明",
                age:26,
                birthday:"1998-02-21",
                address:"北京市朝阳区"
            },{
                name:"王小明",
                age:19,
                birthday:"1990-122-21",
                address:"北京市朝阳区"
            }
        ]
    },
    methods:{
        handleAddData:function () {
            this.data.push({
                name:"刘先天",
                age:24,
                birthday:"1998-09-15",
                address:"上海市闵行区华翔路"
            })
        }
    }
})